CREATE TABLE WR_SECURITY_ROLE (  
  ROLE_ID int NOT NULL,  
  ROLE_ROLE varchar(100) NOT NULL,  
  CONSTRAINT WR_SECURITY_ROLE_PK PRIMARY KEY (ROLE_ID)  
); 

CREATE TABLE WR_SECURITY_USER (  
  USER_ID int NOT NULL, 
  USER_LOGIN varchar(100) NOT NULL,  
  USER_PASSWORD varchar(100) NOT NULL,  
  CONSTRAINT WR_SECURITY_USER_PK PRIMARY KEY (USER_ID) 
);  

CREATE TABLE WR_SECURITY_USER_ROLE (  
  USER_ROLE_ID int NOT NULL, 
  USER_ID int NOT NULL,  
  ROLE_ID int NOT NULL,  
  CONSTRAINT WR_SECURITY_USER_ROLE_PK PRIMARY KEY (USER_ROLE_ID),
  CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES WR_SECURITY_USER (USER_ID), 
  CONSTRAINT ROLE_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES WR_SECURITY_ROLE (ROLE_ID)  
);  

INSERT INTO WR_SECURITY_ROLE(ROLE_ROLE)
VALUES ('admin');
INSERT INTO WR_SECURITY_ROLE(ROLE_ROLE)
VALUES ('user');

INSERT INTO WR_SECURITY_USER(USER_LOGIN,USER_PASSWORD)
VALUES ('admin', 'innosoft');
INSERT INTO WR_SECURITY_USER(USER_LOGIN,USER_PASSWORD)
VALUES ('user', 'innosoft');

INSERT INTO WR_SECURITY_USER_ROLE(USER_ID,ROLE_ID)
VALUES (1, 1);
INSERT INTO WR_SECURITY_USER_ROLE(USER_ID,ROLE_ID)
VALUES (2, 2);

CREATE TABLE WR_MESSAGE (  
  MESG_ID int NOT NULL,  
  MESG_CODE varchar(100) NOT NULL,  
  MESG_LEVEL varchar(100) NOT NULL,  
  MESG_START_DATE date NOT NULL,  
  MESG_END_DATE date NOT NULL,  
  CONSTRAINT WR_MESSAGE_PK PRIMARY KEY (MESG_ID)  
); 

CREATE TABLE WR_CODE (  
  CODE_ID int NOT NULL,  
  CODE_KIND_CODE varchar(100) NOT NULL,  
  CODE_CODE_VALUE varchar(100) NOT NULL,  
  CODE_TEXT varchar(255) NOT NULL,  
  CODE_ISDISPLAY int NOT NULL,  
  CODE_NOTE varchar(255) NOT NULL, 
  CONSTRAINT WR_CODE_PK PRIMARY KEY (CODE_ID)  
); 

CREATE TABLE WR_CUSTOMER (
  CUST_ID int NOT NULL,
  CUST_CUSTOMER_NO varchar(100) NOT NULL,  
  CUST_NAME varchar(100) NOT NULL,
  CUST_PHONENO varchar(100) NOT NULL,
  CUST_EMAIL varchar(100) NOT NULL,
  CUST_ZIPCODE varchar(100) NOT NULL,
  CUST_ADDRESS1 varchar(100) NOT NULL,
  CUST_ADDRESS2 varchar(100) NOT NULL,
  CUST_ADDRESS3 varchar(100) NOT NULL,
  CUST_ISDELETED int NOT NULL,
  CONSTRAINT WR_CUSTOMER_PK PRIMARY KEY (CUST_ID)
);

CREATE TABLE WR_CHARGE (  
  CHRG_ID int NOT NULL,  
  CHRG_CHARGE_NO varchar(100) NOT NULL,  
  CHRG_CUST_ID int NOT NULL,  
  CHRG_PRICE number NOT NULL,  
  CHRG_APP_DIVISION varchar(255) NOT NULL,  
  CHRG_APP_START_DATE date NOT NULL, 
  CHRG_APP_END_DATE date NOT NULL,
  CONSTRAINT WR_CHARGE_PK PRIMARY KEY (CHRG_ID),
  CONSTRAINT WR_CHARGE_FK FOREIGN KEY (CHRG_CUST_ID) REFERENCES WR_CUSTOMER (CUST_ID)
);

CREATE TABLE WR_CALENDAR (  
  CLDR_ID int NOT NULL,  
  CLDR_DATE date NOT NULL,  
  CLDR_DAYCODE varchar(100) NOT NULL,  
  CLDR_NOTE varchar(255) NOT NULL,  
  CONSTRAINT WR_CALENDAR_PK PRIMARY KEY (CLDR_ID)
);