ALTER TABLE WR_RESERVATION MODIFY (RESV_UNIT_NO NUMBER (6));
ALTER TABLE WR_RESERVATION MODIFY (RESV_PARTS_NO NUMBER (6));
ALTER TABLE WR_RESERVATION MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_MESSAGE MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CUSTOMER_TIME MODIFY (CTIM_MAX_UNIT_NO NUMBER (6));
ALTER TABLE WR_CUSTOMER_TIME MODIFY (CTIM_MAX_PARTS_NO NUMBER (6));
ALTER TABLE WR_CUSTOMER_TIME MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CUSTOMER_MEMBER MODIFY (MEBR_POINT NUMBER (6));
ALTER TABLE WR_CUSTOMER_MEMBER MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CUSTOMER MODIFY (CUST_ISDELETED NUMBER (1));
ALTER TABLE WR_CUSTOMER MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CODE MODIFY (CODE_ISDISPLAY NUMBER (1));
ALTER TABLE WR_CODE MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CHARGE_COUNT MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CHARGE MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CALENDAR_ACTIVITY MODIFY (CACT_DETAILS_NO NUMBER (6));
ALTER TABLE WR_CALENDAR_ACTIVITY MODIFY (CACT_OPERATION_FLAG NUMBER (1));
ALTER TABLE WR_CALENDAR_ACTIVITY MODIFY (ISDELETED NUMBER (1));

ALTER TABLE WR_CALENDAR MODIFY (ISDELETED NUMBER (1));
